### ISSUE TITLE
Publish a new release with weekends parameter 

### ISSUE THREAD

**Issue by Toinews** [ogt/workdays#8]
Good afternoon,

Could you please publish a new release which provides the "weekends" parameter to workday and networkdays functions so that I can get it through pypi ?

Thank you very much,
 Antoine,

**Comment by ogt** [comment]
I just published it. (I think so..)
Sorry for the delay.

**Comment by touilleMan** [comment]
Sorry, it seems the last version on pypi is still 1.4 (see https://pypi.python.org/pypi/workdays)
